In [1]:
import numpy as np

In [ ]:
X=np.array([9.2,3.5,2.9])
true_w=np.array([2.55,3.21,9.52])
true_b=0.35
Y=true_w@X+true_b
Y

In [4]:
def relu(num):
    return np.where(num>0,num,0.25*num)

In [6]:
def mean_squared_error(y,y_pred):
    return np.mean(np.pow(y_pred-y,2))
def relu_derivative(num):
    return np.where(num>0,1,0.25)

In [8]:
W=np.random.normal(loc=1,scale=1,size=(3))
epochs=100
i=0
b=np.random.randn()
learning_rate=0.001
while i<epochs:
    #forward pass
    Z=(W@X)+b
    A=relu(Z)
    L=np.pow(A-Y,2)
    # gradient calculation and backpass
    dL_dA=2*(A-Y)
    dA_dZ=relu_derivative(Z)
    dZ_dW=X
    dL_dW=dL_dA*dA_dZ*dZ_dW
    dL_dB=dL_dA*dA_dZ
    # print(f'Z:{Z}\ndL_dW: {dL_dW} \n dL_dB: {dL_dB}')
    W-=learning_rate*dL_dW
    b-=learning_rate*dL_dB
    if i%10==0:
        print(f'loss : {L} \n W:{W} \n b : {b} ')
    i+=1


loss : 2252.23844049971 
 W:[1.94369833 0.97921538 1.38371269] 
 b : -0.03728100007428779 
loss : 18.902644891900703 
 W:[4.88153989 2.09687249 2.30977144] 
 b : 0.2820496037494006 
loss : 0.15864660574304532 
 W:[5.15068251 2.19926371 2.39460987] 
 b : 0.31130423624384684 
loss : 0.0013314933258139138 
 W:[5.1753393  2.20864401 2.40238212] 
 b : 0.31398432237445045 
loss : 1.1174991537776957e-05 
 W:[5.17759817 2.20950336 2.40309416] 
 b : 0.3142298514088287 
loss : 9.378975730202455e-08 
 W:[5.17780511 2.20958209 2.40315939] 
 b : 0.3142523449048527 
loss : 7.871610944228664e-10 
 W:[5.17782407 2.2095893  2.40316536] 
 b : 0.314254405587267 
loss : 6.606505962730607e-12 
 W:[5.1778258  2.20958996 2.40316591] 
 b : 0.3142545943712607 
loss : 5.5447253996041895e-14 
 W:[5.17782596 2.20959002 2.40316596] 
 b : 0.31425461166620916 
loss : 4.653594307754639e-16 
 W:[5.17782598 2.20959003 2.40316597] 
 b : 0.31425461325064036 


In [36]:
## BackPropagation for layer
W=np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2]
])
B= np.array([0.1, 0.2, 0.3])
X=np.array([1,2,3,4])
def relu(arr):
    return np.maximum(arr,0)
def relu_derivative(arr):
    return np.where(arr>0,1,0)
W,B

(array([[0.1, 0.2, 0.3, 0.4],
        [0.5, 0.6, 0.7, 0.8],
        [0.9, 1. , 1.1, 1.2]]),
 array([0.1, 0.2, 0.3]))

In [ ]:
epochs=100
learning_rate=0.001
for i in range(epochs):
    # forward pass
    Z=np.dot(W,X)+B
    A=relu(Z)
    Y=np.sum(A)
    L=Y**2
    #back pass
    dL_dY=2*Y
    dY_dA=np.ones_like(A)
    dA_dZ=relu_derivative(Z)
    dL_dZ=dL_dY*dY_dA*dA_dZ
    dL_dW=np.outer(dL_dZ,X)
    
    W-=learning_rate*dL_dW
    B-=learning_rate*dL_dZ
    print(f"Loss : {L}")
    
    

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

outer_products = A[:, :, None] * B[:, None, :]

In [5]:
A[:,:,None]

array([[[1],
        [2]],

       [[3],
        [4]]])

In [4]:
np.sum(outer_products,axis=0)

array([[26, 30],
       [38, 44]])

In [2]:
class DenseLayer:
    def __init__(self,num_of_inputs,num_of_neurons):
        self.W=np.random.randn(num_of_neurons,num_of_inputs)
        self.B=np.random.randn(num_of_neurons).reshape((1,num_of_neurons))
    
    def forward(self,inputs):
        self.inputs=inputs
        self.output=np.dot(inputs,self.W.T)+self.B
        return self.output
    
    def backward(self,d_outputs):
        self.d_weights=np.dot(self.inputs.T,d_outputs)
        self.d_biases=np.sum(d_outputs,axis=0,keepdims=True)
        self.d_inputs=np.dot(d_outputs,self.W)
